#****** Public Testing *******
sqlname    = "my-terraform-sql"
sqlregion  = "asia-south1"
sqltier    = "db-f1-micro"
sqlversion = "MYSQL_8_0"
vpcsql = "vpcsqlterra"
subnetsql = true
staticip = "staticsqlip"
vmname = "sqlvmname"
vmtype = "e2-medium"
vmzone = "asia-south1-a"
region = "asia-south1"
sqlfirewall = "sqlvmfirewall"
sqluser = "sqlvmuser"
dbname = "sqldb"